DROP DATABASE testDB;
CREATE DATABASE testDB;
USE testDB;
CREATE TABLE Scores(id int NOT NULL AUTO_INCREMENT, date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, file_name VARCHAR(45) NOT NULL, score VARCHAR(45), CONSTRAINT id_pk PRIMARY KEY(id));
                        